### ISSUE TITLE
Я хочу создать диалоговое окно для ввода cookie и id

### ISSUE THREAD

**Issue by waffflezz** [waffflezz/Genshin-manager#2]
Окно сохраняет файлы печенек и id для дальнейшей работы программы.

Подзадачи:
- [ ]  Сделать диалоговое окно #2
- [ ]  Написать back-end для сохранения результатов #3
- [ ]  Сделать красивый дизайн #4
